version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running pytest...
      - pytest tests/test_assert_python.py --junitxml=report.xml

artifacts:
  files:
    - report.xml
